### ISSUE TITLE
psyplot in 2020

### ISSUE THREAD

**Issue by Chilipp** [Chilipp/psyplot#12]
This issue is for discussing new features that we would like to implement within the next year (2020). I'd like to make this open for everyone to poste his or her ideas (pinging @MuellerSeb and @Try2Code) for things that would be nice to be implemented.

As such, this is mainly a collection of ideas, and everything that is posted here will get his own issue under the [psyplot in 2020 milestone](https://github.com/Chilipp/psyplot/milestone/1) (but of course you are kindly invited to create such an issue yourself).

This helps me personally to make a plan for this framework and to discuss it with the members in my institute. But I would like to emphasize that I am very much appreciating contributions from other developers. psyplot has a huge potential for interactive data analysis of climate data, but this becomes at some point difficult for a single maintainer...

Here is my personal wishlist and please add, whatever you have:

**General features**
- [ ] 3D visualization using vtk (see https://github.com/Chilipp/psy-vtk)
- [ ] Exporting psyplot projects as scripts (see https://github.com/Chilipp/psyplot/issues/4)
- [ ] add animation features (see https://github.com/Chilipp/psyplot/issues/10 and https://github.com/Chilipp/psyplot-gui/issues/7)

**GUI**
- [ ] A more intuitive widget for updating central formatoptions in the GUI (e.g. colorbar, colormap, etc.). This could be implemented as plugins for the GUI in the individual package (psy-simple, psy-maps, etc.) (see https://github.com/Chilipp/psyplot-gui/issues/7#issuecomment-562529774)
- [ ] Generate time-series (or any other dimension) by clicking on a grid cell in a map (such as ncview does it, see https://github.com/Chilipp/psyplot-gui/issues/7#issuecomment-562529774)

**Technical issues**
- [ ] The sharing of formatoptions needs to be improved. The strategy within the `Project.update` method (currently it is using one `Thread` per array in the project) needs to be revised. My suggestions is to rather update all formatoptions (and dimensions) in one single thread using some kind of dependency graph
